### ISSUE TITLE
Cannot work in Node.js

### ISSUE THREAD

**Issue by linwaytin** [BurningTreeC/tiddlywiki-muuri#1]
Hi BTC,

Thanks for this amazing plugin.

Somehow I cannot get it to work under Node.js.
It does show up in the `Plugins` in the side panel,
and I can drag the tiddlers,
but when I click the `1`, which should change the number of columns, nothing happens.

I also do not have the `grid` tab.

**Comment by linwaytin** [comment]
I have tried the single file method.
It behaves the same and does not work.
I notice that my tiddlywiki version is 5.1.22.
Do I need 5.1.23 for this plugin to work?

Thank you.

**Comment by BurningTreeC** [comment]
Hi @linwaytin , thanks for the issue report.

I thought that the modifier variable within the Button action-strings was already present in 5.1.22 but it isn't - and therefor this plugin is not fully compatible with 5.1.22. You would need version 5.1.23 for the columns Button to work.

The Grid Tab is only a Demo on the Demo-page, but I'm thinking about adding it to the plugin

best wishes

**Comment by linwaytin** [comment]
Hi @BurningTreeC ,

Yes, the problem is gone after I upgrade to 5.1.23.

Thank you! Great work!
