### ISSUE TITLE
For Muuri it might be useful to enable DISCUSSIONS on GitHub?

### ISSUE THREAD

**Issue by TiddlyTweeter** [BurningTreeC/tiddlywiki-muuri#2]
You are one of my fav. TW developers.

Muuri is _very sophisticated_. I don't really have Issues so much as _needing guidance_ to grasp how to leverage its complexity best in use!

I was wondering if you might want to enable "Discussions" on this repository? I think that might be a better way to get to use it fully?

Best, TT

**Comment by BurningTreeC** [comment]
Hi @TiddlyTweeter - yes Discussions may make sense. I'll open the Discussion Board

**Comment by TiddlyTweeter** [comment]
Ciao @BurningTreeC. Tx. I'll write there soonish with Muuri related discussion.
